### ISSUE TITLE
Announcement Feature

### ISSUE THREAD

**Issue by mintbomb27** [IEEE-VIT/heimdall#12]
A command where you can announce to a particular channel given the channel id and the message.

Basically, receive the message from the user, receive the channel id as argument, send that particular message to that channel.

**Comment by yagueto** [comment]
Hi! I would be interested in working on this issue. Could you assign it to me?

**Comment by mintbomb27** [comment]
Hey yeah sure! Assigning.

**Comment by yagueto** [comment]
Thanks! Just one thing: as I’m participating in the Hacktoberfest, would you mind adding the “Hacktoberfest” label to the repo? I've noticed that this issue already has it

**Comment by mintbomb27** [comment]
Hey @yagueto You still working on the issue?

**Comment by yagueto** [comment]
Hi, sorry, I was a bit busy yesterday :s. I will try to work on it later today
